// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPRH8XzXVChbpWY2f9qPGNyaCqRUHT0eo',
    appId: '1:929061230268:android:9994ac639af41541a022b9',
    messagingSenderId: '929061230268',
    projectId: 'revox-314e6',
    storageBucket: 'revox-314e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByUvh3XQ8gAuh284rCpdrZvcffu5ZEtzU',
    appId: '1:929061230268:ios:75db480717a73139a022b9',
    messagingSenderId: '929061230268',
    projectId: 'revox-314e6',
    storageBucket: 'revox-314e6.firebasestorage.app',
    iosBundleId: 'com.revox.revoxApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8gOkVFuaRPe16FKiRBDwQqgmBaZlcFwQ',
    appId: '1:929061230268:web:586d690aee4279f6a022b9',
    messagingSenderId: '929061230268',
    projectId: 'revox-314e6',
    authDomain: 'revox-314e6.firebaseapp.com',
    storageBucket: 'revox-314e6.firebasestorage.app',
    measurementId: 'G-0CY2Y4BDCW',
  );

}